export const communityPosts = [
  { id: 'school-breakfast', category: 'Education', date: 'August 25, 2026', title: 'School registration, first day and pancake breakfast', summary: 'Registration and the first day of school are Thursday, August 27. Families are invited to meet the teachers and visit the new classrooms over pancake breakfast on Friday, August 28 from 8–11 a.m.', images: ['/community-updates/facebook-01.jpg'], source: 'Waweyekisik Education Centre' },
  { id: 'haircuts', category: 'Family', date: 'August 24, 2026', title: 'Free back-to-school haircuts', summary: 'Waterhen Lake Prevention is hosting back-to-school haircuts August 25 from 10 a.m.–4 p.m. at the Prevention Resource Office. A meal will be provided.', images: ['/community-updates/facebook-02.jpg'], source: 'Waterhen Lake First Nation' },
  { id: 'clinic-closure', category: 'Health', date: 'August 21, 2026', title: 'Clinic closed August 26', summary: 'The community clinic will be closed all day Wednesday, August 26 for an accreditation meeting.', images: ['/community-updates/facebook-09.jpg'], source: 'Waterhen Lake First Nation' },
  { id: 'jarring-workshop', category: 'Community event', date: 'August 20, 2026', title: 'Learn how to jar berries', summary: 'Everyone is welcome at Peyakoskan on August 21 at 10 a.m. Bring your own berries; jars, coffee and snacks will be provided.', images: ['/community-updates/facebook-03.jpg'], source: 'Waterhen Lake First Nation' },
  { id: 'immunization', category: 'Health', date: 'August 20, 2026', title: 'Walk-in immunization clinic', summary: 'Walk-ins are available August 17–20 from 9 a.m.–4 p.m. at the Waterhen Lake Health Center for immunizations, developmental screening and well-baby checks.', images: ['/community-updates/facebook-04.jpg'], source: 'Waterhen Lake First Nation' },
  { id: 'school-registration', category: 'Education', date: 'August 19, 2026', title: 'WEC school registration is open', summary: 'Registration forms are available from the Waweyekisik Education Centre main office. Staff return August 24 and school begins August 27.', images: ['/community-updates/facebook-05.jpg'], source: 'Waterhen Lake First Nation' },
  { id: 'shop-apprentice', category: 'Employment', date: 'August 15, 2026', title: 'Shop Apprentice opportunity', summary: 'Waterhen Forestry Products LP is accepting applications from Waterhen Lake Band members ages 20–30 for a hands-on shop apprenticeship. The posted deadline was August 21.', images: ['/community-updates/facebook-06.jpg'], source: 'Waterhen Forestry Products LP' },
  { id: 'youth-mentor', category: 'Employment', date: 'August 12, 2026', title: 'Youth Mentor — full-time term position', summary: 'Peyakoskan Family Resource Centre is seeking a Youth Mentor for a full-time term ending March 31, 2027. The posted application deadline was August 26 at 4 p.m.', images: ['/community-updates/facebook-07.jpg', '/community-updates/facebook-08.jpg'], source: 'Waterhen Lake First Nation' },
] as const;
